# Autostart
exec-once=noctalia
exec-once=awww-daemon

# Input
xkb_rules_options=caps:escape # Use capslock as escape key
mouse_accel_profile=0 # Disable mouse acceleration
trackpad_accel_profile=0 # Disable mouse acceleration (Touchpad)
mouse_natural_scrolling=0
tap_to_click=1

# Use scroller window layout by default in all tags/workspaces
tagrule=id:*,layout_name:scroller

# Window Effects
blur=0
shadows=1
animations=1
border_radius=0
focused_opacity=1.0
animation_type_open=slide
animation_duration_open=400

# Borders & Gaps
borderpx=4
no_border_when_single=0
gappih=4
gappiv=4
gappoh=10
gappov=10
smartgaps=0

# Colors
rootcolor=0x201b14ff
bordercolor=0x444444ff
focuscolor=0xc9b890ff
maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

# Keybindings
keymode=default

# Core
bind=SUPER,Return,spawn,kitty
bind=SUPER,D,spawn,noctalia msg panel-toggle launcher
bind=ALT,TAB,focusstack
bind=SUPER,TAB,toggleoverview
bind=SUPER,F,togglefullscreen
bind=SUPER,Q,killclient
bind=SUPER,R,reload_config
bind=SUPER+SHIFT,E,quit

# Focus Navigation
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down

# Tag Switching (1-9)
bind=CTRL,1,view,1
bind=CTRL,2,view,2
bind=CTRL,3,view,3
bind=CTRL,4,view,4
bind=CTRL,5,view,5
bind=CTRL,6,view,6
bind=CTRL,7,view,7
bind=CTRL,8,view,8
bind=CTRL,9,view,9

# Move Window to Tag (1-9)
bind=ALT,1,tag,1
bind=ALT,2,tag,2
bind=ALT,3,tag,3
bind=ALT,4,tag,4
bind=ALT,5,tag,5
bind=ALT,6,tag,6
bind=ALT,7,tag,7
bind=ALT,8,tag,8
bind=ALT,9,tag,9
