[audio]
enable_sounds = true

[backdrop]
blur_intensity = 0.05000000074505806
enabled = true
tint_intensity = 0.0

[bar.default]
end = [ "tray", "notifications", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
margin_edge = 4
margin_ends = 16
padding = 16
radius = 8
scale = 1.1500000953674316
start = [ "control-center", "launcher", "workspaces" ]

[desktop_widgets]
enabled = false

[noctalia_state]
setup_wizard_completed = true

[notification]
position = "top_center"

[osd]
position = "top_center"

[shell]
font_family = "Iosevka NFM"
password_style = "random"
polkit_agent = true

[theme]
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk4", "gtk3", "qt", "niri", "kitty", "yazi", "cava", "btop" ]
    community_ids = [ "discord", "pywalfox", "spicetify" ]

[wallpaper]
directory = "/home/voxi0/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/voxi0/Pictures/Wallpapers/wallhaven_3q35m6.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/voxi0/Pictures/Wallpapers/wallhaven_3q35m6.jpg"

[weather]
auto_locate = true

[widget.brightness]
show_label = false

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
display = "none"